/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RecipeId = IDL.Nat;
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const BlogPostId = IDL.Nat;
export const Timestamp = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'featuredImage' : IDL.Text,
  'createdAt' : Timestamp,
  'publishedAt' : Timestamp,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const Rating = IDL.Record({
  'commenterName' : IDL.Text,
  'recipeId' : RecipeId,
  'createdAt' : Timestamp,
  'score' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
});
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Hard' : IDL.Null,
  'Medium' : IDL.Null,
});
export const DietaryTag = IDL.Variant({
  'Keto' : IDL.Null,
  'GlutenFree' : IDL.Null,
  'Vegan' : IDL.Null,
});
export const Category = IDL.Variant({
  'Desserts' : IDL.Null,
  'Lunch' : IDL.Null,
  'Vegan' : IDL.Null,
  'Breakfast' : IDL.Null,
  'Dinner' : IDL.Null,
});
export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Text,
});
export const Recipe = IDL.Record({
  'id' : RecipeId,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'cookTime' : IDL.Nat,
  'description' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'dietaryTags' : IDL.Vec(DietaryTag),
  'prepTime' : IDL.Nat,
  'category' : Category,
  'ingredients' : IDL.Vec(Ingredient),
});

export const idlService = IDL.Service({
  'addRating' : IDL.Func(
      [RecipeId, IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
      [Result],
      [],
    ),
  'getBlogPost' : IDL.Func([BlogPostId], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getRatings' : IDL.Func([RecipeId], [IDL.Vec(Rating)], ['query']),
  'getRecipe' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], ['query']),
  'getRecipes' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(Category),
        IDL.Opt(DietaryTag),
        IDL.Opt(Difficulty),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Recipe)],
      ['query'],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'submitRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        Difficulty,
        IDL.Vec(DietaryTag),
        IDL.Nat,
        IDL.Nat,
      ],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RecipeId = IDL.Nat;
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const BlogPostId = IDL.Nat;
  const Timestamp = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'featuredImage' : IDL.Text,
    'createdAt' : Timestamp,
    'publishedAt' : Timestamp,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const Rating = IDL.Record({
    'commenterName' : IDL.Text,
    'recipeId' : RecipeId,
    'createdAt' : Timestamp,
    'score' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
  });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Hard' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const DietaryTag = IDL.Variant({
    'Keto' : IDL.Null,
    'GlutenFree' : IDL.Null,
    'Vegan' : IDL.Null,
  });
  const Category = IDL.Variant({
    'Desserts' : IDL.Null,
    'Lunch' : IDL.Null,
    'Vegan' : IDL.Null,
    'Breakfast' : IDL.Null,
    'Dinner' : IDL.Null,
  });
  const Ingredient = IDL.Record({ 'name' : IDL.Text, 'quantity' : IDL.Text });
  const Recipe = IDL.Record({
    'id' : RecipeId,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'cookTime' : IDL.Nat,
    'description' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'dietaryTags' : IDL.Vec(DietaryTag),
    'prepTime' : IDL.Nat,
    'category' : Category,
    'ingredients' : IDL.Vec(Ingredient),
  });
  
  return IDL.Service({
    'addRating' : IDL.Func(
        [RecipeId, IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
        [Result],
        [],
      ),
    'getBlogPost' : IDL.Func([BlogPostId], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getRatings' : IDL.Func([RecipeId], [IDL.Vec(Rating)], ['query']),
    'getRecipe' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], ['query']),
    'getRecipes' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(Category),
          IDL.Opt(DietaryTag),
          IDL.Opt(Difficulty),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Recipe)],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'submitRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          Difficulty,
          IDL.Vec(DietaryTag),
          IDL.Nat,
          IDL.Nat,
        ],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };