/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : BlogPostId,
  'title' : string,
  'content' : string,
  'featuredImage' : string,
  'createdAt' : Timestamp,
  'publishedAt' : Timestamp,
  'author' : string,
  'excerpt' : string,
}
export type BlogPostId = bigint;
export type Category = { 'Desserts' : null } |
  { 'Lunch' : null } |
  { 'Vegan' : null } |
  { 'Breakfast' : null } |
  { 'Dinner' : null };
export type DietaryTag = { 'Keto' : null } |
  { 'GlutenFree' : null } |
  { 'Vegan' : null };
export type Difficulty = { 'Easy' : null } |
  { 'Hard' : null } |
  { 'Medium' : null };
export interface Ingredient { 'name' : string, 'quantity' : string }
export interface Rating {
  'commenterName' : string,
  'recipeId' : RecipeId,
  'createdAt' : Timestamp,
  'score' : bigint,
  'comment' : [] | [string],
}
export interface Recipe {
  'id' : RecipeId,
  'difficulty' : Difficulty,
  'name' : string,
  'createdAt' : Timestamp,
  'cookTime' : bigint,
  'description' : string,
  'instructions' : Array<string>,
  'imageUrl' : string,
  'dietaryTags' : Array<DietaryTag>,
  'prepTime' : bigint,
  'category' : Category,
  'ingredients' : Array<Ingredient>,
}
export type RecipeId = bigint;
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'addRating' : ActorMethod<[RecipeId, bigint, [] | [string], string], Result>,
  'getBlogPost' : ActorMethod<[BlogPostId], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getRatings' : ActorMethod<[RecipeId], Array<Rating>>,
  'getRecipe' : ActorMethod<[RecipeId], [] | [Recipe]>,
  'getRecipes' : ActorMethod<
    [
      [] | [string],
      [] | [Category],
      [] | [DietaryTag],
      [] | [Difficulty],
      [] | [bigint],
    ],
    Array<Recipe>
  >,
  'submitContact' : ActorMethod<[string, string, string, string], Result>,
  'submitRecipe' : ActorMethod<
    [
      string,
      string,
      string,
      Category,
      string,
      string,
      Difficulty,
      Array<DietaryTag>,
      bigint,
      bigint,
    ],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];