/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: BlogPostId;
    title: string;
    content: string;
    featuredImage: string;
    createdAt: Timestamp;
    publishedAt: Timestamp;
    author: string;
    excerpt: string;
}
export type RecipeId = bigint;
export type Timestamp = bigint;
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Rating {
    commenterName: string;
    recipeId: RecipeId;
    createdAt: Timestamp;
    score: bigint;
    comment?: string;
}
export interface Ingredient {
    name: string;
    quantity: string;
}
export type BlogPostId = bigint;
export interface Recipe {
    id: RecipeId;
    difficulty: Difficulty;
    name: string;
    createdAt: Timestamp;
    cookTime: bigint;
    description: string;
    instructions: Array<string>;
    imageUrl: string;
    dietaryTags: Array<DietaryTag>;
    prepTime: bigint;
    category: Category;
    ingredients: Array<Ingredient>;
}
export enum Category {
    Desserts = "Desserts",
    Lunch = "Lunch",
    Vegan = "Vegan",
    Breakfast = "Breakfast",
    Dinner = "Dinner"
}
export enum DietaryTag {
    Keto = "Keto",
    GlutenFree = "GlutenFree",
    Vegan = "Vegan"
}
export enum Difficulty {
    Easy = "Easy",
    Hard = "Hard",
    Medium = "Medium"
}
export interface backendInterface {
    addRating(recipeId: RecipeId, score: bigint, comment: string | null, commenterName: string): Promise<Result>;
    getBlogPost(id: BlogPostId): Promise<BlogPost | null>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getRatings(recipeId: RecipeId): Promise<Array<Rating>>;
    getRecipe(id: RecipeId): Promise<Recipe | null>;
    getRecipes(search: string | null, category: Category | null, dietaryTag: DietaryTag | null, difficulty: Difficulty | null, maxPrepTime: bigint | null): Promise<Array<Recipe>>;
    submitContact(name: string, email: string, subject: string, message: string): Promise<Result>;
    submitRecipe(name: string, email: string, recipeName: string, category: Category, ingredients: string, instructions: string, difficulty: Difficulty, dietaryTags: Array<DietaryTag>, prepTime: bigint, cookTime: bigint): Promise<Result>;
}
import type { BlogPost as _BlogPost, Category as _Category, DietaryTag as _DietaryTag, Difficulty as _Difficulty, Ingredient as _Ingredient, Rating as _Rating, Recipe as _Recipe, RecipeId as _RecipeId, Result as _Result, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRating(arg0: RecipeId, arg1: bigint, arg2: string | null, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addRating(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Result_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRating(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Result_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: BlogPostId): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return result;
        }
    }
    async getRatings(arg0: RecipeId): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatings(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatings(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipe(arg0: RecipeId): Promise<Recipe | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipes(arg0: string | null, arg1: Category | null, arg2: DietaryTag | null, arg3: Difficulty | null, arg4: bigint | null): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return from_candid_Result_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return from_candid_Result_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRecipe(arg0: string, arg1: string, arg2: string, arg3: Category, arg4: string, arg5: string, arg6: Difficulty, arg7: Array<DietaryTag>, arg8: bigint, arg9: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRecipe(arg0, arg1, arg2, to_candid_Category_n20(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_Difficulty_n26(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n30(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
                return from_candid_Result_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRecipe(arg0, arg1, arg2, to_candid_Category_n20(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_Difficulty_n26(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n30(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
            return from_candid_Result_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DietaryTag_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietaryTag): DietaryTag {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Rating_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rating): Rating {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Recipe]): Recipe | null {
    return value.length === 0 ? null : from_candid_Recipe_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecipeId;
    difficulty: _Difficulty;
    name: string;
    createdAt: _Timestamp;
    cookTime: bigint;
    description: string;
    instructions: Array<string>;
    imageUrl: string;
    dietaryTags: Array<_DietaryTag>;
    prepTime: bigint;
    category: _Category;
    ingredients: Array<_Ingredient>;
}): {
    id: RecipeId;
    difficulty: Difficulty;
    name: string;
    createdAt: Timestamp;
    cookTime: bigint;
    description: string;
    instructions: Array<string>;
    imageUrl: string;
    dietaryTags: Array<DietaryTag>;
    prepTime: bigint;
    category: Category;
    ingredients: Array<Ingredient>;
} {
    return {
        id: value.id,
        difficulty: from_candid_Difficulty_n12(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        createdAt: value.createdAt,
        cookTime: value.cookTime,
        description: value.description,
        instructions: value.instructions,
        imageUrl: value.imageUrl,
        dietaryTags: from_candid_vec_n14(_uploadFile, _downloadFile, value.dietaryTags),
        prepTime: value.prepTime,
        category: from_candid_Category_n17(_uploadFile, _downloadFile, value.category),
        ingredients: value.ingredients
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commenterName: string;
    recipeId: _RecipeId;
    createdAt: _Timestamp;
    score: bigint;
    comment: [] | [string];
}): {
    commenterName: string;
    recipeId: RecipeId;
    createdAt: Timestamp;
    score: bigint;
    comment?: string;
} {
    return {
        commenterName: value.commenterName,
        recipeId: value.recipeId,
        createdAt: value.createdAt,
        score: value.score,
        comment: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.comment))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
}): Difficulty {
    return "Easy" in value ? Difficulty.Easy : "Hard" in value ? Difficulty.Hard : "Medium" in value ? Difficulty.Medium : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Keto: null;
} | {
    GlutenFree: null;
} | {
    Vegan: null;
}): DietaryTag {
    return "Keto" in value ? DietaryTag.Keto : "GlutenFree" in value ? DietaryTag.GlutenFree : "Vegan" in value ? DietaryTag.Vegan : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Desserts: null;
} | {
    Lunch: null;
} | {
    Vegan: null;
} | {
    Breakfast: null;
} | {
    Dinner: null;
}): Category {
    return "Desserts" in value ? Category.Desserts : "Lunch" in value ? Category.Lunch : "Vegan" in value ? Category.Vegan : "Breakfast" in value ? Category.Breakfast : "Dinner" in value ? Category.Dinner : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietaryTag>): Array<DietaryTag> {
    return value.map((x)=>from_candid_DietaryTag_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rating>): Array<Rating> {
    return value.map((x)=>from_candid_Rating_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_DietaryTag_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): _DietaryTag {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n20(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag | null): [] | [_DietaryTag] {
    return value === null ? candid_none() : candid_some(to_candid_DietaryTag_n23(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty | null): [] | [_Difficulty] {
    return value === null ? candid_none() : candid_some(to_candid_Difficulty_n26(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Desserts: null;
} | {
    Lunch: null;
} | {
    Vegan: null;
} | {
    Breakfast: null;
} | {
    Dinner: null;
} {
    return value == Category.Desserts ? {
        Desserts: null
    } : value == Category.Lunch ? {
        Lunch: null
    } : value == Category.Vegan ? {
        Vegan: null
    } : value == Category.Breakfast ? {
        Breakfast: null
    } : value == Category.Dinner ? {
        Dinner: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): {
    Keto: null;
} | {
    GlutenFree: null;
} | {
    Vegan: null;
} {
    return value == DietaryTag.Keto ? {
        Keto: null
    } : value == DietaryTag.GlutenFree ? {
        GlutenFree: null
    } : value == DietaryTag.Vegan ? {
        Vegan: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
} {
    return value == Difficulty.Easy ? {
        Easy: null
    } : value == Difficulty.Hard ? {
        Hard: null
    } : value == Difficulty.Medium ? {
        Medium: null
    } : value;
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DietaryTag>): Array<_DietaryTag> {
    return value.map((x)=>to_candid_DietaryTag_n23(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
